# Generated by Django 5.2.7 on 2025-11-05 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_order_orderitem_order_shopping_or_user_id_5dab01_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_reviewed',
            field=models.BooleanField(default=False, verbose_name='是否已评价'),
        ),
        migrations.CreateModel(
            name='OrderItemReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评价内容')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='评分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='shopping.orderitem', verbose_name='订单商品')),
                ('spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_reviews', to='shopping.productspu', verbose_name='关联SPU')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_reviews', to=settings.AUTH_USER_MODEL, verbose_name='评价用户')),
            ],
            options={
                'verbose_name': '订单商品评价',
                'verbose_name_plural': '订单商品评价',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['spu', 'created_at'], name='shopping_or_spu_id_6fc677_idx'), models.Index(fields=['user'], name='shopping_or_user_id_a271ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('not_received', '未收到货'), ('not_as_described', '商品与描述不符'), ('quality_issue', '质量问题'), ('wrong_item', '发错货'), ('other', '其他原因')], max_length=50, verbose_name='退款原因')),
                ('description', models.TextField(verbose_name='详细说明')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='退款金额')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已同意'), ('rejected', '已拒绝'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='处理状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('admin_remark', models.TextField(blank=True, verbose_name='管理员备注')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_request', to='shopping.order', verbose_name='关联订单')),
            ],
            options={
                'verbose_name': '退款申请',
                'verbose_name_plural': '退款申请',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='shopping_re_status_875e64_idx')],
            },
        ),
    ]
