# Generated by Django 5.2.7 on 2025-11-06 13:32

import django.db.models.deletion
import shopping.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_add_shipping_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shopping.models.review_image_upload_path, verbose_name='图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_images', to='shopping.orderitemreview', verbose_name='关联评价')),
            ],
            options={
                'verbose_name': '评价图片',
                'verbose_name_plural': '评价图片',
                'ordering': ['created_at'],
            },
        ),
    ]
