# Generated by Django 5.2.7 on 2025-11-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_orderitemreviewimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('alipay', '支付宝'), ('wechat', '微信支付'), ('stripe', 'Stripe'), ('mock', '模拟支付')], max_length=20, verbose_name='支付方式'),
        ),
    ]
