# Generated by Django 5.2.7 on 2025-11-15 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0007_alter_video_video_type'),
        ('shopping', '0009_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='shopping.productspu', verbose_name='关联商品'),
        ),
    ]
